# Generated by Django 5.2.4 on 2025-07-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_keyword_rename_langauge_doctor_language_news_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
