# Generated by Django 5.2.4 on 2025-07-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='description',
            field=models.CharField(default='Image description', help_text='Brief description', max_length=100),
        ),
    ]
