# Generated by Django 5.2.4 on 2025-07-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_newsimage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('alt_text', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='news',
            old_name='context',
            new_name='content',
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
