# Generated by Django 5.2.4 on 2025-07-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(default='Article summary', max_length=250),
            preserve_default=False,
        ),
    ]
