# Generated by Django 5.2.4 on 2025-08-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_news_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='medicalunit',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='main_image_url',
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='doctors/'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(default='image', upload_to='gallery/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalunit',
            name='image',
            field=models.ImageField(blank=True, upload_to='medical_units/'),
        ),
        migrations.AddField(
            model_name='news',
            name='main_image',
            field=models.ImageField(default='main_image', upload_to='news_main_images/'),
            preserve_default=False,
        ),
    ]
