# Generated by Django 5.2.4 on 2025-08-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_remove_doctor_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='medicalunit',
            name='image',
            field=models.ImageField(upload_to='medical_units/'),
        ),
    ]
